#!/usr/bin/env bash
# configures Nginx to run and listen on port 80 in an Ubuntu container
sudo apt-get update
sudo apt-get -y install nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx start
