#!/usr/bin/env bash
#printing "bad luck" in 4th loop iteration, printing "good luck" in 8th loop iteration and printing "Best school" in the left iterations  
i=1
while [ $i -le 10  ]
do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
